version: '3'
services:
  api:
    image: clojure:temurin-19-lein
    working_dir: /usr/local/api
    command: lein repl :headless :host 0.0.0.0 :port 42001
    ports:
      - 42001:42001
    volumes:
      - maven:/root/.m2
      - .:/usr/local/api

  web:
    build:
      context: ./dev
      dockerfile: node_java.Dockerfile
    working_dir: /usr/local/web
    ports:
      - 9630:9630
    volumes:
      - .:/usr/local/web
      - shadow_maven:/root/.m2
    command: yarn dev

  gateway:
    volumes:
      - ./dev/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:3000
    networks:
      default:
        aliases:
          - shared-hosting.lvh.me
    image: nginx:1.23.1-alpine

volumes:
  maven:
  shadow_maven:
